# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8ecd995856fbaa0e5b5ee6985cc04701cfc054c3876f9929b64abcc49fcce0ca3d1760cc924e27521d00364a39423f202e0a712d9cf412662e2f6bed5d759c0

test:
  secret_key_base: 297295c69ba1a3e4640d202b86483c37be40304978ee4000bf761c8545d5eb847676acfcd16dd756a6a882f7ced618b9ac0e30b5379e8ea01434f0f2c77f7211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
